{
 "title": "Kubernetes Pods/Containers Resource Utilization Dashboard",
 "description": "Display usage of resources by pod or container in kubernetes cluster.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Deployments Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Deployments Unavailable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Pods Per Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\"}) ",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Pods Running ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Containers Per Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Containers Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Pods/Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "POD CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[5m])) by (pod, container)",
     "legendFormat": "Current: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}",
     "legendFormat": "Requested: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ pod }}"
    }
   ]
  },
  {
   "title": "POD CPU Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) by (pod, container, namespace)",
     "legendFormat": "{{Requested Cores}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) by (pod, container, namespace)",
     "legendFormat": "{{Limit Cores}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[5m])) by (pod, container)",
     "legendFormat": "{{Usage Cores}}"
    },
    {
     "expr": "sum(\r\n      rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[5m])\r\n    ) by (pod, container,)\r\n      /\r\n    sum(\r\n      container_spec_cpu_quota{image!=\"\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"} / container_spec_cpu_period{image!=\"\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}\r\n    ) by (pod, container)",
     "legendFormat": "{{CPU Util}}"
    }
   ]
  },
  {
   "title": "POD Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"$pod\",container!=\"POD\",container!=\"\",image!=\"\", namespace=\"$namespace\",container=~\"$container\"}",
     "legendFormat": "Current: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\",pod=~\"$pod\", container!=\"POD\", container=~\"$container\"}",
     "legendFormat": "Requested: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$pod\", container!=\"POD\", container=~\"$container\"}",
     "legendFormat": "Limit: {{ pod }}"
    }
   ]
  },
  {
   "title": "POD Memory Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", container!=\"POD\",resource=\"memory\"}) by (pod, container, namespace) / (1024*1024) ",
     "legendFormat": "{{Requested RAM}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) by (pod, container, namespace) / (1024*1024) ",
     "legendFormat": "{{Limit RAM}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\",container!=\"POD\",container!=\"\",image!=\"\", namespace=\"$namespace\",container=~\"$container\"}) by (pod,container) ",
     "legendFormat": "{{Usage RAM}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\",container!=\"POD\",container!=\"\",image!=\"\", namespace=\"$namespace\",container=~\"$container\"}) by (container,pod) / sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) by (container,pod)",
     "legendFormat": "{{Memory Util}}"
    }
   ]
  },
  {
   "title": "POD Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])  ",
     "legendFormat": "TX : {{ pod }}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "RX : {{ pod }}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{pod=\"$pod\",container=\"$container\"}[5m])) by (container)",
     "legendFormat": " usage: {{container}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=\"$pod\",container=\"$container\",resource=\"cpu\"}) by (container)",
     "legendFormat": "request: {{container}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=\"$pod\",container=\"$container\",resource=\"cpu\"}) by (container)",
     "legendFormat": "limit: {{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container=\"$container\",pod=\"$pod\"} / (1024*1024)) by (container)",
     "legendFormat": " usage: {{container}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{container=\"$container\",pod=\"$pod\",resource=\"memory\"}) by (container) / (1024*1024)",
     "legendFormat": "request: {{container}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=\"$pod\",container=\"$container\",resource=\"memory\"}) by (container) / (1024*1024)",
     "legendFormat": "limit: {{container}}"
    }
   ]
  }
 ]
}